### ISSUE TITLE
rootnet.

### ISSUE THREAD

**Issue by Intel-i80486-DX4** [PlutoSolutions/Abyss#13]
want a rootNET account for cracking purposes? DM me. (sun.misc.Unsafe#9691)

**Comment by HausemasterIssue** [comment]
A rootNET crack would be beyond swag.

**Comment by master7720** [comment]
> want a rootNET account for cracking purposes? DM me. (sun.misc.Unsafe#9691)

i own rootNET and its it's terrible

**Comment by GentlemanMC** [comment]
> > want a rootNET account for cracking purposes? DM me. (sun.misc.Unsafe#9691)
> 
> i own rootNET and its it's terrible

But why would u even buy it

**Comment by master7720** [comment]
> > > want a rootNET account for cracking purposes? DM me. (sun.misc.Unsafe#9691)
> > 
> > 
> > i own rootNET and its it's terrible
> 
> But why would u even buy it

idk i saw it and it looked cool

**Comment by master7720** [comment]
but it was a waste

**Comment by master7720** [comment]
the og kami has a better ca then rootnet

**Comment by GentlemanMC** [comment]
lmfao

**Comment by HausemasterIssue** [comment]
It would still be a nice piece of software to be able to use and see.

**Comment by GentlemanMC** [comment]
> It would still be a nice piece of software to be able to use and see without wasting your money. Archival purposes 🤓

truje

**Comment by master7720** [comment]
> It would still be a nice piece of software to be able to use and see without wasting your money. Archival purposes 🤓

i guess

**Comment by mr-nv** [comment]
rootnet was cracked like a year ago and i doubt that it even had any updates

**Comment by mr-nv** [comment]
https://www.reddit.com/r/minecraftclients/comments/laqz58/cracked_minecraft_hacked_client_rootnet_011/

**Comment by mr-nv** [comment]
https://mega.nz/file/zOxlGDIb#6cueAjGHkJUmPnXkK-fzxEnDkap9mhvJqfXt2Vua-Zw

**Comment by mr-nv** [comment]
shits worse than catalyst

**Comment by HausemasterIssue** [comment]
Thanks @mr-nv very cool!
