### ISSUE TITLE
не робит на линуксе ааааааа

### ISSUE THREAD

**Issue by Shuttafaka** [PlutoSolutions/Abyss#15]
кароче когда запускаешь на линуксе пишет Blocked Web Account пофиксите пожалуйста

**Comment by mr-nv** [comment]
это ты мне в телеге писал? Если да я все от ветил нахуйэ. жди

**Comment by mr-nv** [comment]
жди хуй знает сколько пока мне не лень будет

**Comment by mr-nv** [comment]
хуй нам хуй вам https://github.com/PlutoSolutions/Abyss/issues/7#issuecomment-1140217728
