### ISSUE TITLE
Me when decryption failed

### ISSUE THREAD

**Issue by gadiiell** [PlutoSolutions/Abyss#20]
![image](https://user-images.githubusercontent.com/95395808/227803727-019499be-4146-44a6-abff-52ec7f82a50a.png)
My face when decyption failed :
![image](https://user-images.githubusercontent.com/95395808/227803772-7fe4cb27-89b7-41a3-a650-ebda26c1dcea.png)

**Comment by mr-nv** [comment]
you did something wrong
