### ISSUE TITLE
с голосовым ассистентом надеюсь?

### ISSUE THREAD

**Issue by oyzipfile** [PlutoSolutions/Abyss#6]
БУРРОВ, АВТОКРИСТАЛ, СУРРАУНД, БУРРОВВВ бууууроовввв

**Comment by master7720** [comment]
surround* burrow*

**Comment by ZenovJB** [comment]
> БУРРОВ, АВТОКРИСТАЛ, СУРРАУНД, БУРРОВВВ бууууроовввв

ебало закрой а то я боеголовку запущу по твоему бункеру

**Comment by trapathon** [comment]
ахаххаха сука зенов обожаю твои панчи братан

**Comment by mr-nv** [comment]
да тут есть ассистент
дестракшн попробовал пиздец хуйня
