### ISSUE TITLE
Windows only again

### ISSUE THREAD

**Issue by Intel-i80486-DX4** [PlutoSolutions/Abyss#7]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/55558592/168162232-9bed52f1-eb3e-4429-8d1f-3c8a0c3b1d9e.png">
Nice.

**Comment by ZenovJB** [comment]
тебя ебе

**Comment by mr-nv** [comment]
blame their drm for that
buy me an abyss account and a mac and i might add mac support

**Comment by mr-nv** [comment]
im not sure if you can do that on mac but on linux theres a virtual machine with gpu passthrough support so it runs like a real machine (very little fps drop and better game support)
look that up, maybe it works on mac. and configure it right so you can run games with anticheats (installing a vm just for minecraft is dumb)

**Comment by Intel-i80486-DX4** [comment]
why not open source it?

**Comment by mr-nv** [comment]
no point due to how their drm works

**Comment by mr-nv** [comment]
ill need to recrack it for every platform

**Comment by mr-nv** [comment]
can you find function addresses in binaries in ida/ghidra? if yes you should be able to reverse qq's crack just fine
otherwise no point in opensourcing this shit

**Comment by TudbuT** [comment]
> can you find function addresses in binaries in ida/ghidra? if yes you should be able to reverse qq's crack just fine otherwise no point in opensourcing this shit

you can find similar ASM snippets. if you gave us the ghidra project, we could simply find similar functions and port the diff, because ASM on windows and linux is quite similar for the most part.

**Comment by mr-nv** [comment]
yeah i know that its different, ill install linux as a second os in a few days and try to port the crack to it
this shouldnt be hard since it looks like linux and mac rocket drm binaries have symbols
![image](https://user-images.githubusercontent.com/31269663/168698994-e7a0961f-66db-4a55-8c58-c0f9457d7ede.png)

**Comment by mr-nv** [comment]
dont know if current keys that i return in functions that i hook will work tho

**Comment by mr-nv** [comment]
> dont know if current keys that i return in functions that i hook will work tho

yeah it looks like linux/mac versions of rocketdrm are different from the windows one, or maybe im just retarded
either way i couldnt get the crack to work on linux

https://crystalpvp.ru/abyss/linuxrocketdrmshit.zip

i left some comments if you have an abyss license and you wish to log your own keys for the crack
dont ask me how to compile this thing

**Comment by mr-nv** [comment]
no point due to how their drm works

пт, 13 мая 2022 г., 13:56 Intel-i80486-DX4 ***@***.***>:

**Comment by 0x7DB** [comment]
code::blocks project? i'll have a go at porting it to macos and linux later. (thanks for the comments btw)

**Comment by mr-nv** [comment]
no not code blocks, codelite or something idk i dont use linux
i guess your porting attempt was unsuccessful

пн, 14 нояб. 2022 г., 01:46 rd-131648 ***@***.***>:
